# Generated by Django 4.2.5 on 2023-10-04 10:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('fname', models.CharField(default='', max_length=255)),
                ('lname', models.CharField(default='', max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.TextField()),
                ('contact', models.CharField(default='', max_length=20)),
                ('profile', models.ImageField(default='', upload_to='Admin/')),
                ('address', models.TextField(default='')),
                ('Otp', models.IntegerField(default=0)),
                ('OtpCount', models.IntegerField(default=0)),
                ('OtpStatus', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=True)),
                ('role', models.CharField(choices=[('country-admin', 'country-admin'), ('city-admin', 'city-admin'), ('branch-manager', 'branch-manager')], default='', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BookServices',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('start_service_datetime', models.DateTimeField(blank=True, null=True)),
                ('start_service_latitude', models.DecimalField(decimal_places=8, default=0.0, max_digits=11)),
                ('start_service_longitude', models.DecimalField(decimal_places=8, default=0.0, max_digits=11)),
                ('end_service_datetime', models.DateTimeField(blank=True, null=True)),
                ('end_service_latitude', models.DecimalField(decimal_places=8, default=0.0, max_digits=11)),
                ('end_service_longitude', models.DecimalField(decimal_places=8, default=0.0, max_digits=11)),
                ('estimate_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('waiting_time', models.DateTimeField(blank=True, null=True)),
                ('total_distance_travel', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total_time', models.DateTimeField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('customer_paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('ride_status', models.CharField(choices=[('captain-arrived', 'captain-arrived'), ('start-service', 'start-service'), ('end-service', 'end-service')], default='', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Captain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('fname', models.CharField(default='', max_length=255)),
                ('lname', models.CharField(default='', max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.TextField()),
                ('contact', models.CharField(default='', max_length=20, unique=True)),
                ('profile', models.ImageField(default='', upload_to='Captain/Profile')),
                ('address', models.TextField(default='')),
                ('Otp', models.IntegerField(default=0)),
                ('OtpCount', models.IntegerField(default=0)),
                ('OtpStatus', models.BooleanField(default=False)),
                ('no_of_attempts_allowed', models.IntegerField(default=3)),
                ('no_of_wrong_attempts', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CaptainServiceHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('captain_profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('company_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('wallet_before', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('wallet_after', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('book_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webApi.bookservices')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CaptainVehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('cnic', models.IntegerField(default=0)),
                ('cnic_front_image', models.ImageField(default='', upload_to='Captain/Cnic/')),
                ('cnic_back_image', models.ImageField(default='', upload_to='Captain/Cnic/')),
                ('vehicle_number', models.CharField(default='', max_length=50)),
                ('numberplate_image', models.ImageField(default='', upload_to='Captain/Vehicle_Numberplate/')),
                ('vehicle_document_image', models.ImageField(default='', upload_to='Captain/Vehicle_Document/')),
                ('license_number', models.CharField(default='', max_length=50)),
                ('license_front_image', models.ImageField(default='', upload_to='Captain/License/')),
                ('license_back_image', models.ImageField(default='', upload_to='Captain/License/')),
                ('approval_status', models.BooleanField(default=False)),
                ('approval_message', models.CharField(default='', max_length=50)),
                ('captain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webApi.captain')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CaptainWallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('wallet_status', models.BooleanField(default=False)),
                ('captain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webApi.captain')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('fname', models.CharField(default='', max_length=255)),
                ('lname', models.CharField(default='', max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.TextField()),
                ('contact', models.CharField(default='', max_length=20, unique=True)),
                ('profile', models.ImageField(default='', upload_to='Customer/Profile')),
                ('address', models.TextField(default='')),
                ('Otp', models.IntegerField(default=0)),
                ('OtpCount', models.IntegerField(default=0)),
                ('OtpStatus', models.BooleanField(default=False)),
                ('no_of_attempts_allowed', models.IntegerField(default=3)),
                ('no_of_wrong_attempts', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('country', models.CharField(default='', max_length=50)),
                ('city', models.CharField(default='', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SuperAdmin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('fname', models.CharField(default='', max_length=255)),
                ('lname', models.CharField(default='', max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.TextField()),
                ('contact', models.CharField(default='', max_length=20)),
                ('profile', models.ImageField(default='', upload_to='SuperAdmin/')),
                ('address', models.TextField(default='')),
                ('Otp', models.IntegerField(default=0)),
                ('OtpCount', models.IntegerField(default=0)),
                ('OtpStatus', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VehicleImages',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('image', models.ImageField(default='', upload_to='Captain/Vehicle_Image/')),
                ('captain_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webApi.captainvehicle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VehicleCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='', max_length=50)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webApi.place')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SuperAdminWhitelistToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webApi.superadmin')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='', max_length=50)),
                ('vehicle_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webApi.vehiclecategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerWhitelistToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webApi.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerWallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('wallet_status', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webApi.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerServiceHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('customer_paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('wallet_before', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('wallet_after', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('book_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webApi.bookservices')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webApi.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('initial_cost', models.CharField(default='', max_length=50)),
                ('price_per_km', models.CharField(default='', max_length=50)),
                ('waiting_cost', models.CharField(default='', max_length=50)),
                ('profit_percentage', models.CharField(default='', max_length=50)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webApi.service')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyProfitHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('profit_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('profit_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('captain_service_history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webApi.captainservicehistory')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webApi.place')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CaptainWhitelistToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('captain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webApi.captain')),
            ],
        ),
        migrations.CreateModel(
            name='captainWalletTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('payment_type', models.CharField(choices=[('paypal', 'paypal'), ('card', 'card')], default='', max_length=50)),
                ('payment_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('captain_wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webApi.captainwallet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='captainvehicle',
            name='vehicle_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webApi.vehiclecategory'),
        ),
        migrations.AddField(
            model_name='captainservicehistory',
            name='captain_wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webApi.captainwallet'),
        ),
        migrations.AddField(
            model_name='bookservices',
            name='captain_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webApi.captainvehicle'),
        ),
        migrations.AddField(
            model_name='bookservices',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webApi.customer'),
        ),
        migrations.AddField(
            model_name='bookservices',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webApi.service'),
        ),
        migrations.CreateModel(
            name='BookServiceDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('sender_name', models.CharField(default='', max_length=50)),
                ('sender_contact', models.CharField(default='', max_length=50)),
                ('receiver_name', models.CharField(default='', max_length=50)),
                ('receiver_address', models.CharField(default='', max_length=50)),
                ('receiver_contact', models.CharField(default='', max_length=50)),
                ('courier_size', models.IntegerField(default=0)),
                ('shop_name', models.CharField(default='', max_length=50)),
                ('shop_latitude', models.DecimalField(decimal_places=8, default=0.0, max_digits=11)),
                ('shop_langitude', models.DecimalField(decimal_places=8, default=0.0, max_digits=11)),
                ('item', models.TextField(default='')),
                ('item_description', models.TextField(default='')),
                ('estimate_price', models.IntegerField(default=0)),
                ('services_choice', models.CharField(choices=[('courier', 'courier'), ('shopping', 'shopping')], default='', max_length=50)),
                ('book_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webApi.bookservices')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdminWhitelistToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webApi.admin')),
            ],
        ),
        migrations.AddField(
            model_name='admin',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webApi.place'),
        ),
    ]
